version: "3.9"
services:
  dbpost:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_lr9_1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_scripts/init_lr9_1.sql:/docker-entrypoint-initdb.d/init_lr9_1.sql
    ports:
      - 5432:5432
